emit:
  - "@typespec/http-server-csharp"
  - "@typespec/http-server-js"
options:
  "@typespec/http-server-csharp":
    emitter-output-dir: "{project-root}/../servers/aspnet/generated"  
  "@typespec/http-server-js":
    emitter-output-dir: "{project-root}/../servers/node/tsp-output/@typespec/http-server-js"  
    express: true
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/../clients/java"
