emit:
  - "@typespec/http-server-csharp"
  - "@typespec/http-client-csharp"
  - "@typespec/http-client-java"
options:
  "@typespec/http-server-csharp":
    emitter-output-dir: "{project-root}/../servers/aspnet/generated"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{project-root}/../clients/dotnet"
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/../clients/java"
